import { storage } from "./storage";

export async function seedDefaultScopes() {
  const existing = await storage.getDefaultScope();
  if (existing) return;

  const orgs = await storage.getOrganizations();
  let defaultOrg = orgs.find(o => o.slug === "orfheuss-demo");
  if (!defaultOrg) {
    defaultOrg = await storage.createOrganization({
      name: "ORFHEUSS Demo",
      slug: "orfheuss-demo",
      description: "Standaard demonstratie-organisatie met klinisch gate-profiel (EU AI Act + IC governance)",
      sector: "healthcare",
      gateProfile: "CLINICAL",
    });
  }

  await storage.createScope({
    name: "LEYEN",
    description: "EU AI Act + IC klinische governance scope",
    status: "LOCKED",
    orgId: defaultOrg.id,
    categories: [
      {
        name: "EU_AI_PROHIBITED",
        label: "Verboden AI (Onaanvaardbaar Risico)",
        status: "BLOCK",
        keywords: [
          "social scoring", "sociaal kredietsysteem", "manipulatie", "subliminal",
          "kwetsbare groepen uitbuiting", "biometrische massa-identificatie",
          "real-time biometrie", "gezichtsherkenning massa", "emotieherkenning werkplek",
          "emotieherkenning onderwijs", "predictive policing", "voorspellend politiewerk",
          "gedragsmanipulatie", "dark patterns ai", "scoring overheidsdiensten",
        ],
        escalation: "AI Office / Toezichthouder",
      },
      {
        name: "EU_AI_HIGH_RISK",
        label: "Hoog Risico (Annex III)",
        status: "ESCALATE_HUMAN",
        keywords: [
          "biometrisch", "kritieke infrastructuur", "onderwijs toelating",
          "werkgelegenheid selectie", "kredietbeoordeling", "rechtshandhaving",
          "migratie", "asiel", "rechtspraak ai", "medisch hulpmiddel",
          "veiligheidssysteem", "sollicitatie ai", "cv screening ai",
          "grenscontrole", "autonome besluitvorming", "geautomatiseerde beslissing",
          "bijzondere persoonsgegevens", "kwetsbare groepen", "fundamentele rechten",
          "critical infrastructure",
        ],
        escalation: "DPO / Legal / Conformiteitsbeoordelaar",
      },
      {
        name: "EU_AI_GPAI",
        label: "General Purpose AI",
        status: "ESCALATE_REGULATORY",
        keywords: [
          "foundation model", "large language model", "llm", "gpt", "general purpose",
          "generatieve ai", "chatbot breed inzetbaar", "systemisch risico",
          "training data", "compute threshold", "10^25 flops", "gpai", "basismodel",
        ],
        escalation: "AI Office / DPO",
      },
      {
        name: "EU_AI_LIMITED_RISK",
        label: "Beperkt Risico (Transparantie)",
        status: "PASS_WITH_TRANSPARENCY",
        keywords: [
          "chatbot", "deepfake", "ai-gegenereerde content", "synthetische media",
          "transparantieverplichting", "ai-label", "ai-disclosure",
          "emotieherkenning beperkt", "biometrische categorisatie", "ai-interactie melding",
        ],
        escalation: "Transparantieverplichting",
      },
      {
        name: "EU_AI_MINIMAL",
        label: "Minimaal Risico",
        status: "PASS",
        keywords: [
          "spamfilter", "ai gaming", "aanbevelingssysteem", "zoekalgoritme",
          "autocorrect", "vertaalsoftware", "voorraadoptimalisatie", "routeplanning",
          "beeldverbetering", "contentfilter",
        ],
        escalation: null,
      },
      {
        name: "PRIVACY_DOSSIER",
        label: "Privacy / Dossier",
        status: "ESCALATE_HUMAN",
        keywords: [
          "dossier", "medisch dossier", "patiëntgegevens", "ouders",
          "avg", "wgbo", "beroepsgeheim", "inzagerecht", "deel_dossier",
        ],
        escalation: "DPO",
      },
    ],
    documents: [],
    rules: [
      {
        ruleId: "EU_AI_ART_5",
        layer: "EU",
        domain: "AI",
        title: "Verboden AI-praktijken",
        description: "AI-systemen voor sociale scoring, manipulatieve technieken, biometrische classificatie op gevoelige kenmerken, en voorspellende politie zijn verboden.",
        action: "BLOCK",
        overridesLowerLayers: true,
        source: "EU AI Act",
        article: "Artikel 5",
      },
      {
        ruleId: "EU_AI_ART_6",
        layer: "EU",
        domain: "AI",
        title: "Hoog-risico AI-systemen",
        description: "AI-systemen in kritieke infrastructuur, onderwijs, werkgelegenheid, rechtshandhaving en migratie vereisen conformiteitsbeoordeling.",
        action: "ESCALATE_HUMAN",
        overridesLowerLayers: true,
        source: "EU AI Act",
        article: "Artikel 6-7",
      },
      {
        ruleId: "EU_AI_ART_50",
        layer: "EU",
        domain: "AI",
        title: "Transparantieverplichtingen",
        description: "AI-systemen die interageren met personen, emotieherkenning, biometrische categorisering en deepfakes moeten transparant zijn.",
        action: "PASS_WITH_TRANSPARENCY",
        overridesLowerLayers: true,
        source: "EU AI Act",
        article: "Artikel 50",
      },
      {
        ruleId: "EU_AI_ART_51",
        layer: "EU",
        domain: "AI",
        title: "GPAI-modellen",
        description: "Aanbieders van General Purpose AI-modellen moeten technische documentatie bijhouden en samenwerken met toezichthouders.",
        action: "ESCALATE_REGULATORY",
        overridesLowerLayers: true,
        source: "EU AI Act",
        article: "Artikel 51-56",
      },
      {
        ruleId: "EU_AI_ART_95",
        layer: "EU",
        domain: "AI",
        title: "Minimaal-risico AI",
        description: "AI-systemen met minimaal risico mogen vrij worden ingezet. Vrijwillige gedragscodes worden aangemoedigd.",
        action: "PASS",
        overridesLowerLayers: false,
        source: "EU AI Act",
        article: "Artikel 95",
      },
      {
        ruleId: "NL_UAVG_BIO",
        layer: "NATIONAL",
        domain: "AI",
        title: "UAVG biometrische gegevens",
        description: "Verwerking van biometrische gegevens ter identificatie is verboden tenzij noodzakelijk voor authenticatie of beveiliging.",
        action: "BLOCK",
        overridesLowerLayers: true,
        source: "UAVG (NL)",
        article: "Art. 29",
      },
      {
        ruleId: "NL_WGBO_AI",
        layer: "NATIONAL",
        domain: "AI",
        title: "WGBO AI in zorg",
        description: "AI-ondersteuning bij medische besluitvorming vereist informatie aan de patiënt en toestemming. De arts blijft eindverantwoordelijk.",
        action: "ESCALATE_HUMAN",
        overridesLowerLayers: false,
        source: "WGBO (NL)",
        article: "Art. 7:448 BW",
      },
      {
        ruleId: "NL_AP_ALGO",
        layer: "NATIONAL",
        domain: "AI",
        title: "AP toezicht algoritmes",
        description: "De Autoriteit Persoonsgegevens houdt toezicht op geautomatiseerde besluitvorming. Organisaties moeten een DPIA uitvoeren bij hoog-risico AI.",
        action: "ESCALATE_REGULATORY",
        overridesLowerLayers: false,
        source: "Autoriteit Persoonsgegevens",
        article: "AVG Art. 35",
      },
      {
        ruleId: "REG_GGD_AI",
        layer: "REGIONAL",
        domain: "AI",
        title: "GGD regionaal protocol AI",
        description: "Regionale GGD-protocollen voor AI-gebruik in publieke gezondheid. Aanvullende transparantie-eisen bij contactonderzoek.",
        action: "PASS_WITH_TRANSPARENCY",
        overridesLowerLayers: false,
        source: "GGD Protocol",
        article: "Regionaal",
      },
      {
        ruleId: "MUN_ALGO_REG",
        layer: "MUNICIPAL",
        domain: "AI",
        title: "Gemeentelijk algoritmeregister",
        description: "Gemeente vereist registratie van algoritmes in het openbaar algoritmeregister. Publieke verantwoording.",
        action: "PASS_WITH_TRANSPARENCY",
        overridesLowerLayers: false,
        source: "Gemeentelijke verordening",
        article: "Lokaal",
      },
    ],
    isDefault: "true",
  });
}
